# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_instagram', '0006_auto_20180727_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_instagram.Profile'),
        ),
    ]
